#!/usr/bin/env python3
import os, glob, re
from datetime import datetime
from xml.etree import ElementTree as ET

# ───────────────────────────────────────────────────────
#   CONFIGURATION → change if you ever move domains/folders
BASE_URL   = "https://blog.reservedcannabis.ca"
POSTS_DIR  = "posts"
OUTPUT     = "blog-feed.html"
RSS_FILE   = "rss.xml"   # generated by your rss_generator
# ───────────────────────────────────────────────────────

def parse_rss_items(rss_path):
    """Parse our rss.xml for title, link, date, and enclosure (image)."""
    tree  = ET.parse(rss_path)
    items = []
    for item in tree.findall("./channel/item"):
        title = item.findtext("title")
        link  = item.findtext("link")
        date  = datetime.strptime(item.findtext("pubDate"),
                                  "%a, %d %b %Y %H:%M:%S %z") \
                                  .strftime("%b %-d, %Y")
        # optional <enclosure url="…">
        img = item.find("enclosure")
        img_url = img.get("url") if img is not None else ""
        items.append((title, link, date, img_url))
    return items

def make_card(title, link, date, img_url):
    img_html = f'<img src="{img_url}" alt="{title}">' if img_url else ""
    return f"""
    <a class="rss-card" href="{link}">
      {img_html}
      <div class="rss-card-content">
        <h2>{title}</h2>
        <time>{date}</time>
      </div>
    </a>
    """

def main():
    items = parse_rss_items(RSS_FILE)

    html = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Cannabis Blog – Reserved Cannabis</title>
  <style>
    body {{ background:#d0b08b; font-family:system-ui,sans-serif; margin:2rem; }}
    h1 {{ font-size:2.5rem; margin-bottom:1rem; }}
    .rss-grid {{
      display:grid;
      grid-template-columns: repeat(auto-fit,minmax(280px,1fr));
      gap:1.5rem;
    }}
    .rss-card {{
      background:#fff;
      border-radius:12px;
      overflow:hidden;
      text-decoration:none;
      color:#111;
      box-shadow:0 4px 12px rgba(0,0,0,0.1);
      display:flex;
      flex-direction:column;
    }}
    .rss-card img {{
      width:100%; height:160px; object-fit:cover;
    }}
    .rss-card-content {{ padding:1rem; flex:1; }}
    .rss-card-content h2 {{ margin:0 0 .5rem; font-size:1.25rem; }}
    .rss-card-content time {{ color:#666; font-size:.9rem; }}
  </style>
</head>
<body>
  <h1>Latest Articles</h1>
  <div class="rss-grid">
    {"".join(make_card(*it) for it in items)}
  </div>
</body>
</html>
"""
    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write(html.strip())

if __name__ == "__main__":
    main()